banking/bank/urls.py
from django.urls import path
from . import views
app_name='bank'
urlpatterns = [

    path('',views.Home,name='home'),
    path('login/',views.login_page,name='login_page'),
    path('register/',views.Register_page,name='register'),
    path('form/',views.form_page,name='forms'),
    path('final/',views.final_page,name='final'),
    path('register2/',views.Register2,name='register2')
]

banking/banking/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("bank.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

banking/bank/models.py
from django.db import models

# Create your models here.
class bank(models.Model):
    name=models.CharField(max_length=250)
    password=models.TextField()

banking/bank/views.py
from django.shortcuts import render
from . models import bank
# Create your views here.
def Home(request):
    return render(request,'index.html')
def login_page(request):
    return render(request,'login_page.html')
def Register_page(request):
    bank_items=bank.objects.all()
    return render(request,'register.html',{'bank_details':bank_items})
def form_page(request):
    return render(request,'form_page.html')
def final_page(request):
    return render(request,'final_page.html')
def Register2(request):
    return render(request,'register2.html')

banking/templates/final_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body{
        background-color:aqua;
        font-size: large;
        font-family: 'Times New Roman', Times, serif;
        font-weight: 200;
        color: white;

        background-image: url("{% static 'final.jpg' %}");
        background-size:cover;
        }
    </style>
</head>
<body>
<h1 style="text-align:center;color: white;">Thank you...Your Application is Submitted</h1>
<p style="padding-left:300px;color: white;">Click below link to go back home page</p>
<a style="padding-left:300px;" href="{% url 'bank:home' %}" class="btn btn-info">Home</a>
</body>
</html>

banking/templates/form_page.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Application Form</title>
  <script>
    var district_branches = {
      "Ernakulam": ["Aluva", "Edapally"],
      "Kottayam": ["Pala", "Kanjirappalli", "Erimayur"],
      "Palakkad": ["olavakkod", "Mundur", "Parali"]
    };

    function updateBranches() {
      var district = document.getElementById("district").value;
      var branches = district_branches[district];
      var branch_select = document.getElementById("branch");
      branch_select.innerHTML = "";
      for (var i = 0; i < branches.length; i++) {
        var branch = branches[i];
        var option = document.createElement("option");
        option.value = branch;
        option.text = branch;
        branch_select.add(option);
      }
    }
  </script>
  <style>
     body {

      background-image: url("{% static 'form.jpg' %}");
      background-size:cover;
    }

    h1 {
      color: #4CAF50;
      text-align: center;
    }

    form {
      background-color: rgba(9, 53, 67, 0.844);
      color:white;
      width: 50%;
      margin: auto;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0px 0px 10px 0px rgba(0,1,0,0.2);
    }

    label {

      margin-top: 10px;
      margin-bottom: 5px;
      font-weight: bold;
    }

  </style>
</head>
<body>
	<form action="{% url 'bank:final' %}">
		<label for="name">Name:</label><br>
		<input type="text" id="name" name="name"><br><br>

		<label for="dob">DOB:</label><br>
		<input type="date" id="dob" name="dob"><br><br>

		<label for="age">Age:</label><br>
		<input type="number" id="age" name="age"><br><br>

		<label for="gender">Gender:</label><br>
		<select id="gender" name="gender">
			<option value="male">Male</option>
			<option value="female">Female</option>
			<option value="other">Other</option>
		</select><br><br>

		<label for="phone">Phone Number:</label><br>
		<input type="tel" id="phone" name="phone"><br><br>

		<label for="email">Mail ID:</label><br>
		<input type="email" id="email" name="email"><br><br>

		<label for="address">Address:</label><br>
		<textarea id="address" name="address"></textarea><br><br>

		<form action="{% url 'bank:home' %}">
    <label for="district">District:</label><br>
    <select id="district" onchange="updateBranches()">
      <option value="Ernakulam">Ernakulam</option>
      <option value="Kottayam">Kottayam</option>
      <option value="Palakkad">Palakkad</option>
    </select>
    <br>
    <label for="branch">Branch:</label><br>
    <select id="branch"></select> <br><br>


		<label for="account_type">Account Type:</label><br>
		<select id="account_type" name="account_type">
			<option value="savings">Savings Account</option>
			<option value="current">Current Account</option>
		</select><br><br>

		<label for="materials">Materials Provided:</label>
		<input type="checkbox" id="debit_card" name="debit_card" value="debit_card">
		<label for="debit_card">Debit Card</label>
		<input type="checkbox" id="credit_card" name="credit_card" value="credit_card">
		<label for="credit_card">Credit Card</label>
		<input type="checkbox" id="cheque_book" name="cheque_book" value="cheque_book">
		<label for="cheque_book">Cheque Book</label><br><br>

		<a href=""><button>Submit</button></a> <br><br>

	</form>
		<a style="padding-left:373px;" href="{% url 'bank:home' %}"><button>Logout</button></a>
</body>
</html>

banking/templates/index.html
{% extends 'navbar.html' %}
{% load static %}

{% block body %}
<div class="card mb-3">
  <img class="card-img-top" style="height:550px; width:100%;" src="{% static 'index.jpeg' %}" alt="Card image cap">
  <div class="card-body" style="text-align:center;">
    <h5 class="card-title">Click here to login</h5>
    <a href="{% url 'bank:login_page' %}" class="btn btn-info">Login</a>
  </div>
</div>
{% endblock %}

banking/templates/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Glassmorphism login Form Tutorial in html css</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
    background-image: url("{% static 'log.jpg' %}");
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>

    <div class="background">
<!--        <div class="shape"></div>-->
<!--        <div class="shape"></div>-->
    </div>
    <form>
        <h3>Login Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Email or Phone" id="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password">
        <a href="{% url 'bank:home' %}">HomePage</a>

        <div class="social">
          <div class="go"> <a href="{% url 'bank:register' %}"> <i class="fab fa-google"></i> Register</a></div>

          <div class="fb"><a href="{% url 'bank:forms' %}"> <i class="fab fa-google"></i>  Login</a></div>
        </div>
    </form>
</body>
</html>

banking/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">IBI Bank</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bank:login_page' %}">Login <span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bank:register' %}">Register</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Branches
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram">Thiruvananthapuram</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Pathanamthitta_district">Pathanamthitta</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kottayam">Kottayam</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Alappuzha">Alappuzha</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad_district">Palakkad</a>
          <div class="dropdown-divider"></div>
        </div>
      </li>
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>
  </div>
</nav>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
{% block body %}
{% endblock %}
</body>
</html>

banking/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Register page</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
    background-image: url("{% static 'log.jpg' %}");
    background-size:cover;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}

form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">

    </div>
    <form>
        <h3>Register Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Email or Phone" id="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Password" id="password">
        <label for="password">Confirm Password</label>
        <input type="password" placeholder="Confirm Password" id="password">


        <div class="go"> <a href="{% url 'bank:register2' %}"> <i class="fab fa-google"></i> Register</a></div>


    </form>
</body>
</html>

banking/templates/register2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body{
        background-color: #080710;
        background-image: url("{% static 'log.jpg' %}");
        background-size:cover;
    </style>
</head>
<body>
<h1 style="color:white;">Click here to register </h1>
<a style="padding-left:300px;color:white;" href="{% url 'bank:forms' %}" class="btn btn-info">Register</a>
</body>
</html>